# Generated by Django 5.0.14 on 2026-05-19 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedresume',
            old_name='template_name',
            new_name='template_style',
        ),
        migrations.AddField(
            model_name='generatedresume',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generatedresume',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('experience_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume')),
            ],
        ),
    ]
