# Generated by Django 5.0.14 on 2026-05-19 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_rename_template_name_generatedresume_template_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atsanalysis',
            name='keyword_match',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='atsanalysis',
            name='project_impact_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='atsanalysis',
            name='weak_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='atsanalysis',
            name='job_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ats_analyses', to='resumes.jobdescription'),
        ),
    ]
