# Generated by Django 6.0.5 on 2026-05-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_atsanalysis_keyword_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='year',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='duration',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
