# Generated by Django 6.0.5 on 2026-05-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_certification_year_experience_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='year',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
